name: Go
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Format check
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        make fmt-check

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: 'latest'

    - name: Test
      run: go mod vendor && make test
      env:
        SORACOM_EMAIL_FOR_TEST: ${{ secrets.SORACOM_EMAIL_FOR_TEST }}
        SORACOM_PASSWORD_FOR_TEST: ${{ secrets.SORACOM_PASSWORD_FOR_TEST }}
        SORACOM_AUTHKEY_ID_FOR_TEST: ${{ secrets.SORACOM_AUTHKEY_ID_FOR_TEST }}
        SORACOM_AUTHKEY_FOR_TEST: ${{ secrets.SORACOM_AUTHKEY_FOR_TEST }}
